#!/usr/bin/env python3
"""Regenerate sources/governance-versions.md from the tags of the governance repository.

The governance repository (Wiess-College/governance) holds the college's governing documents (Constitution,
Bylaws, Rules, Housing Rules), with one tagged commit per ratified version. This script keeps a copy of those
tags in sources/, which a copy kept by hand would let fall behind whenever a new version is tagged. It runs git
on a local checkout of that repository (git must be installed; nothing is fetched over the network) and
rewrites one file from scratch:

    sources/governance-versions.md    a Markdown table with one row per tag: tag, date, title, files changed

A page can include the table with `--8<-- "governance-versions.md"` (pymdownx.snippets also looks in
sources/); no page does yet, and the "Versions reviewed" table on the Governance page is kept by hand, so
running this script does not change the site.

Give it the checkout's folder, set TFWKB_GOVERNANCE_REPO, or put `governance_repo:` in tfwkb.config.yml
(see tools/repository_folders.py), and run it after a new version is tagged:

    python3 tools/import_governance_changes.py ../governance
    TFWKB_GOVERNANCE_REPO=../governance python3 tools/import_governance_changes.py

A relative folder is relative to where you run it (in tfwkb.config.yml, to the repository root). The folder
on the command line wins over everything else, even when it is an empty string, and any further arguments
are ignored. GOVERNANCE_REPO, the variable's older name, still works when TFWKB_GOVERNANCE_REPO is not set. On success it prints
"wrote <file> (<count> versions)".

Without a checkout it prints "no governance checkout given; keeping the committed table" to stderr, leaves
the file alone and exits 0. This is what happens in CI (.github/workflows/pages.yml runs it with neither), so
CI keeps the committed table: run it locally and commit the result. A folder counts as a
checkout only if it contains a .git folder, so a git worktree or submodule, where .git is a file, gets the
same message.

Each row is built from the tagged commit: the date is its author date, the title is its subject line, and
the files are the names from `git show --stat` on lines that mention ".md" and mention neither "CHANGES" nor
"README". Rows are sorted by date. Tags whose names start with "seed-" are left out. A checkout with no
tags, such as a clone made without them, writes a table with no rows.

If git fails, for example on a broken .git folder that is not inside another git repository, it stops with
a subprocess.CalledProcessError traceback (exit status 1) and nothing has been written, because every git
command runs before the file is opened. Without git installed it stops the same way with FileNotFoundError.
If the broken .git folder is inside another git repository, git uses that repository instead, and its tags
are written to the table with exit status 0.

Some rows can come out wrong; check the table before committing it:

    a "|" in a commit subject      splits the row into extra columns; it is not escaped.
    an annotated tag's message     git show prints it above the file list, so a message line mentioning
                                   ".md" is listed as a file, the whole line.
    a long file path               git show --stat shortens it to ".../<end of path>", and that is listed.
    a renamed file                 listed as git prints it, "old.md => new.md".
    a tag on a file or folder      not an error: the row has no date or title, and sorts to the top; Files
                                   lists the file's lines, or the folder's names, that mention ".md".
"""

import os
import subprocess
import sys
from typing import NamedTuple

from repository_folders import governance_folder

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VERSIONS_TABLE_FILE = os.path.join(REPO_ROOT, "sources", "governance-versions.md")

GENERATED_NOTICE = "<!-- generated by tools/import_governance_changes.py from the governance repo; do not edit -->"

# Tags whose names start with this are left out of the table.
SEED_TAG_PREFIX = "seed-"


class GovernanceVersion(NamedTuple):
    """One ratified text: its tag in the governance repository and the facts its table row shows."""

    tag: str  # the tag's name in the governance repository, e.g. "v2020-02-12"; shown in backticks in the first column
    date: str  # the tagged commit's author date, YYYY-MM-DD
    subject: str  # the tagged commit's subject line, shown as the version's title
    markdown_files: str  # the Markdown files the tagged commit changed, sorted and joined with ", "


def main(arguments: list[str]) -> None:
    """Find the governance checkout, read a version from each of its tags, and write the table."""
    governance_repo = find_governance_checkout(arguments)
    if not governance_repo:
        print("no governance checkout given; keeping the committed table", file=sys.stderr)
        return

    versions = read_governance_versions(governance_repo)
    write_versions_table(versions)
    print(f"wrote {VERSIONS_TABLE_FILE} ({len(versions)} versions)")


def find_governance_checkout(arguments: list[str]) -> str:
    """Return the checkout folder from the command line, environment or config, or "" if it has no .git folder."""
    if arguments:
        governance_repo = arguments[0]
    elif os.environ.get("GOVERNANCE_REPO") and not os.environ.get("TFWKB_GOVERNANCE_REPO"):
        governance_repo = os.environ["GOVERNANCE_REPO"]
    else:
        governance_repo = str(governance_folder() or "")
    if governance_repo and os.path.isdir(os.path.join(governance_repo, ".git")):
        return governance_repo
    return ""


def read_governance_versions(governance_repo: str) -> list[GovernanceVersion]:
    """Return a version for each tag in the checkout, except the "seed-" tags, oldest tag first."""
    versions = []
    for tag in run_git(governance_repo, "tag", "--sort=creatordate").splitlines():
        if tag.startswith(SEED_TAG_PREFIX):
            continue
        versions.append(
            GovernanceVersion(
                tag=tag,
                date=run_git(governance_repo, "log", "-1", "--format=%ad", "--date=short", tag),
                subject=run_git(governance_repo, "log", "-1", "--format=%s", tag),
                markdown_files=list_markdown_files_changed(governance_repo, tag),
            )
        )
    return versions


def list_markdown_files_changed(governance_repo: str, tag: str) -> str:
    """Return the Markdown files the tagged commit changed, except CHANGES and README, joined with ", ".

    The names come from the file list of `git show --stat`, whose lines look like
    " constitution.md | 12 +++---". Lines are kept or dropped by searching the whole line, so this also
    picks up an annotated tag's message lines (git show prints the tag before the commit), and a
    shortened ".../" path is listed as git printed it.
    """
    stat_lines = run_git(governance_repo, "show", "--stat", "--format=", tag).splitlines()
    # as git --stat prints them: relative to the checkout's root, possibly shortened to ".../"
    changed_subpaths = set()
    for stat_line in stat_lines:
        if ".md" in stat_line and "CHANGES" not in stat_line and "README" not in stat_line:
            changed_subpath, _, _ = stat_line.partition("|")
            changed_subpaths.add(changed_subpath.strip())
    return ", ".join(sorted(changed_subpaths))


def write_versions_table(versions: list[GovernanceVersion]) -> None:
    """Rewrite sources/governance-versions.md as a Markdown table with one row per version, sorted by date.

    Versions with the same date are ordered by their whole row text, which starts with the tag, so the
    order from `git tag --sort=creatordate` does not survive. Sorting on the row text rather than the tag
    alone keeps the order the table has always had: "v1-x" sorts before "v1", because "-" comes before
    the backtick that closes "`v1`".
    """
    rows_with_dates = [(version.date, format_table_row(version)) for version in versions]
    table_lines = [
        GENERATED_NOTICE,
        "",
        "| Tag | Date | Version | Files |",
        "|---|---|---|---|",
        *(row for _, row in sorted(rows_with_dates)),
        "",  # so the file ends with a newline
    ]
    with open(VERSIONS_TABLE_FILE, "w", encoding="utf-8") as versions_table:
        versions_table.write("\n".join(table_lines))


def format_table_row(version: GovernanceVersion) -> str:
    """Return the version's row of the Markdown table."""
    return f"| `{version.tag}` | {version.date} | {version.subject} | {version.markdown_files} |"


def run_git(governance_repo: str, *git_arguments: str) -> str:
    """Run a git command in the checkout and return what it prints, without surrounding whitespace."""
    return subprocess.check_output(["git", "-C", governance_repo, *git_arguments], text=True).strip()


if __name__ == "__main__":
    main(sys.argv[1:])
