#!/usr/bin/env python3
"""Regenerate sources/governance-versions.md from the governance repo's tags.

The governance repository (Wiess-College/governance) holds one tagged commit per ratified text.
This script reads its tags and commit messages and writes a Markdown table that the
Governance pages include with `--8<-- "governance-versions.md"`. Point it at a checkout:

    python3 tools/import_governance_changes.py ~/projects/wiess-archive/wiess-governance
    GOVERNANCE_REPO=../governance python3 tools/import_governance_changes.py

Without a checkout it leaves the committed table alone and exits 0 (so CI can run it).
"""
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "sources", "governance-versions.md")


def git(repo, *args):
    return subprocess.check_output(["git", "-C", repo, *args], text=True).strip()


def main():
    repo = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("GOVERNANCE_REPO", "")
    if not repo or not os.path.isdir(os.path.join(repo, ".git")):
        print("no governance checkout given; keeping the committed table", file=sys.stderr)
        return
    tags = git(repo, "tag", "--sort=creatordate").splitlines()
    rows = []
    for t in tags:
        if t.startswith("seed-"):
            continue
        date = git(repo, "log", "-1", "--format=%ad", "--date=short", t)
        subject = git(repo, "log", "-1", "--format=%s", t)
        files = git(repo, "show", "--stat", "--format=", t).splitlines()
        docs = ", ".join(sorted({ln.split("|")[0].strip() for ln in files if ".md" in ln and "CHANGES" not in ln and "README" not in ln}))
        rows.append((date, f"| `{t}` | {date} | {subject} | {docs} |"))
    rows = [r for _, r in sorted(rows)]
    body = ["<!-- generated by tools/import_governance_changes.py from the governance repo; do not edit -->",
            "", "| Tag | Date | Version | Files |", "|---|---|---|---|", *rows, ""]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(body))
    print(f"wrote {OUT} ({len(rows)} versions)")


if __name__ == "__main__":
    main()
