"""List every photograph shown on a Record page, with its caption, credit and date (editor, 2026-10-05).

This file is the one place editors change a photo's caption or move it to another page. Nothing reads
it directly except tools/apply_photos.py, which copies it onto the Record pages, the Photographs page
and the manifest; run that script after every change here.

Each entry in PHOTO_PLACEMENTS is a tuple of seven strings, in this order: photo_subpath (relative to
docs/assets/photos/), gallery_key (a key of GALLERY_PAGES), caption, credit_plain, credit_citation,
date and topic. The caption is plain text, because it also becomes the lightbox title and the manifest
caption. credit_citation is the Markdown citation shown under the image, or "" when there is nothing to
cite. Entries are plain tuples rather than named records so that adding one takes nothing but
quotes and commas; apply_photos.py gives the fields their names.

Some credits and citations shared by many photos are kept in the constants below, so a correction is
made once.
"""

RICE_HISTORY_CORNER_CONSTRUCTION_CITATION = "[@rhc 2012-12-04 wiess-hall-construction-1949]"
WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT = "Rice University, Woodson Research Center, via Rice History Corner"
DELANY_2002_CREDIT = "Colin Delany '91, 'wiess college | abandoned', August 2002"
SOURCE_NOT_RECORDED_CREDIT = "TFWKB photo collection; source not recorded"

PHOTO_PLACEMENTS = [
    # --- Old Wiess: construction (1949-50)
    ("photos-old-wiess-construction/wiess-construction-1.jpg", "oldwiess",
     "1 March 1949: the site staked out with batter boards on open grass, a crane and site hut beyond. The label reads 'Wm. M. Rice Institute Dormitory Building, Staub & Rather, Architects, W. S. Bellows Construction Corp., Contractors'.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION, "1949-03-01", "Old Wiess, construction"),
    ("photos-old-wiess-construction/photography-wiesshallconstruction-4-1-49.jpg", "oldwiess",
     "1 April 1949: footings and forms, with a baseball game against A&M in the background.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION + " [@rhc 2012-12-04 wiess-hall-construction-1949 comment by almadenmike, 5 Dec 2012]", "1949-04-01", "Old Wiess, construction"),
    ("photos-old-wiess-construction/wiess-construction-2.jpg", "oldwiess",
     "1 April 1949 (no. 2): the foundation forms across the site.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION, "1949-04-01", "Old Wiess, construction"),
    ("photos-old-wiess-construction/wiess-construction-4.jpg", "oldwiess",
     "1 August 1949: the steel frame of the walkway roofs.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION, "1949-08-01", "Old Wiess, construction"),
    ("photos-old-wiess-construction/photography-wiesshallconstruction-11-1-49.jpg", "oldwiess",
     "1 November 1949: along a finished walkway.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION, "1949-11-01", "Old Wiess, construction"),
    ("photos-old-wiess-construction/wiess1949.jpg", "oldwiess",
     "1 December 1949: a two-storey wing complete, its balconies open to the yard; the ground still bare.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION, "1949-12-01", "Old Wiess, construction"),
    ("photos-old-wiess-construction/moritz-wiesshallcompletion-3-10-50.jpg", "oldwiess",
     "'Wiess Hall completion', 10 March 1950 (date from the file's title): the finished building behind a lone pine.",
     WOODSON_VIA_RICE_HISTORY_CORNER_CREDIT, RICE_HISTORY_CORNER_CONSTRUCTION_CITATION, "1950-03-10", "Old Wiess, construction"),
    # --- Old Wiess: later views
    ("photos-outside/wiess-and-west-halls-nov-2-1950-gift-of-pender-turnbull-438.jpg", "oldwiess",
     "Wiess and West Halls from above, 2 November 1950 (date and 'gift of Pender Turnbull' from the file name).",
     SOURCE_NOT_RECORDED_CREDIT, "", "1950-11-02", "Old Wiess"),
    ("photos-outside/oldwiesscollege-9-69.jpg", "oldwiess",
     "Old Wiess College across an open field, September 1969 (date from the file name).",
     SOURCE_NOT_RECORDED_CREDIT, "", "1969-09", "Old Wiess"),
    ("photos-outside/aerialviewgymnasium-1969.jpg", "oldwiess",
     "Aerial view of the campus around the gymnasium, 1969 (date and subject from the file name); Old Wiess's west wing stood next to the gym.",
     SOURCE_NOT_RECORDED_CREDIT, "[@riceinfo-history]", "1969", "Old Wiess"),
    # --- Old Wiess: Delany, Aug 2002
    ("photos-old-wiess/details-photo6.jpg", "oldwiess",
     "The 1975 plaque: 'Wiess College, established in memory of Harry Carothers Wiess (1887–1948)', with the Plutarch line on Socrates. Transcribed on the Old Wiess page.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/spaces-photo13.jpg", "oldwiess",
     "The entrance under the WIESS COLLEGE lettering, abandoned, August 2002.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/hallways-photo2.jpg", "oldwiess",
     "Two storeys of rooms opening onto balconies over a courtyard, August 2002.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/hallways-photo1.jpg", "oldwiess",
     "An outdoor balcony walkway, August 2002: every Old Wiess room opened onto one.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/spaces-photo1.jpg", "oldwiess",
     "'Between commons and backabowl' (Delany's caption), August 2002.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/spaces-photo3.jpg", "oldwiess",
     "A glass-walled common room with yellow chairs, seen from outside, August 2002.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/spaces-photo5.jpg", "oldwiess",
     "A paved patio with benches under the trees, August 2002.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    ("photos-old-wiess/windows-photo3.jpg", "oldwiess",
     "Steel-framed windows in the brick, August 2002.",
     DELANY_2002_CREDIT, "[@edesigns-old-wiess-2002]", "2002-08", "Old Wiess, 2002"),
    # --- Commons
    ("photos-old-wiess/jello-night-weiss-college-c1996-3-008-commons.jpg", "commons",
     "Jello Night in the Old Wiess Commons, c.1996 (date and event from the file name).",
     SOURCE_NOT_RECORDED_CREDIT, "", "c.1996", "The Commons"),
    ("photos/commons.jpg", "commons",
     "The New Wiess Commons: long tables, yellow chairs, the glass wall onto the Acabowl.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224839 http://teamwiess.com/newstudents/rooms/commons.jpg]", "by 2017", "The Commons"),
    ("photos-outside/family.jpg", "commons",
     "TEAM FAMILY WIESS painted across the Commons windows, with 'Welcome' beside it.",
     "teamwiess.com, 'acapics', by 2019", "[@wb 20190928044413 http://teamwiess.com/acapics/family.jpg]", "by 2019", "The Commons"),
    ("photos-outside/commons-2.jpg", "commons",
     "The New Wiess Commons from the Acabowl lawn: two storeys of glass behind a sunscreen, a tree in front.",
     SOURCE_NOT_RECORDED_CREDIT, "", "undated (after 2002)", "The Commons"),
    # --- New Wiess
    ("photos-outside/rescolleges.jpg", "newwiess",
     "The Commons across the Acabowl lawn and path.",
     "teamwiess.com, 2016", "[@wb 20160506224855 http://teamwiess.com/res/rescolleges.jpg]", "by 2016", "New Wiess"),
    ("photos-outside/pink.jpg", "newwiess",
     "The Commons lit up at dusk, seen from the Acabowl.",
     "teamwiess.com, 'acapics', 2017", "[@wb 20170602224647 http://teamwiess.com/acapics/pink.jpg]", "by 2017", "New Wiess"),
    ("photos-outside/wing.jpg", "newwiess",
     "A residential wing over the Acabowl at dusk, ivy on its screens, a tower beyond.",
     SOURCE_NOT_RECORDED_CREDIT, "", "undated", "New Wiess"),
    ("photos-outside/darkhall.jpg", "newwiess",
     "An open-air corridor behind the ivy-covered metal screens, at dusk.",
     "teamwiess.com, 'acapics', 2017", "[@wb 20170602224650 http://teamwiess.com/acapics/darkhall.jpg]", "by 2017", "New Wiess"),
    ("photos-outside/dark-aisle-4.jpg", "newwiess",
     "Another corridor at dusk: brick on one side, screen and ivy on the other.",
     "teamwiess.com, 'acapics', 2017", "[@wb 20170602225337 http://teamwiess.com/acapics/dark-aisle.jpg]", "by 2017", "New Wiess"),
    ("photos-outside/upper.jpg", "newwiess",
     "The glazed upper storey of the Commons at dusk, seen from an upper floor.",
     SOURCE_NOT_RECORDED_CREDIT, "", "undated", "New Wiess"),
    ("photos-outside/snow-1.jpg", "newwiess",
     "Snow on the Acabowl lawn and picnic tables.",
     "teamwiess.com, 'acapics', by February 2018", "[@wb 20180223224559 http://teamwiess.com/acapics/snow.jpg]", "by 2018-02", "New Wiess"),
    # --- Acabowl
    ("photos-outside/wiess-four-square-1991.jpg", "acabowl",
     "Four-square on the paved court of the Old Wiess Acabowl, 1991 (date from the file name), balconies behind.",
     SOURCE_NOT_RECORDED_CREDIT, "[@handbook-1994]", "1991", "The Acabowl"),
    ("photos-outside/acabowl-2017.jpg", "acabowl",
     "The New Wiess Acabowl: lawn, a picnic table and the ivy-hung wing.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224834 http://teamwiess.com/newstudents/rooms/acabowl.jpg]", "by 2017", "The Acabowl"),
    ("photos/aca-slide.jpg", "acabowl",
     "A rendering of a spiral slide from an upper balcony down to the lawn. Compare the 2002 'Proposed Wiess Acaslide'.",
     SOURCE_NOT_RECORDED_CREDIT, "[@wb 20021013235815 http://www.teamwiess.com:80/pow.html]", "undated", "The Acabowl"),
    # --- Terraces / Toke
    ("photos-outside/bacaterrace.jpg", "terraces",
     "The large paved terrace on the South Servery roof, with its shade structure, at sunset. The file is named 'bacaterrace'.",
     SOURCE_NOT_RECORDED_CREDIT, "", "undated", "The terraces"),
    ("photos-outside/fourthterrace.jpg", "terraces",
     "The fourth-floor balcony (the Bacaterrace of the 2014–17 books): benches and rail, the playing fields beyond.",
     SOURCE_NOT_RECORDED_CREDIT, "", "undated", "The terraces"),
    ("photos-outside/terrace-sky.jpg", "terraces",
     "Sunset over the playing fields from an upper-floor balcony rail, probably the same fourth-floor balcony.",
     SOURCE_NOT_RECORDED_CREDIT, "", "undated", "The terraces"),
    ("photos-people/wiessicles.jpg", "terraces",
     "TOKE painted on a graffiti-covered table: an O-Week photograph of 2022, the earliest written trace of the name.",
     "teamwiess.com, O-Week 2022", "[@wb 20220709040142 http://teamwiess.com/images/oweek2022/wiessicles.jpg]", "2022", "The terraces"),
    # --- Rooms
    ("photos-inside-rooms/alcove.jpg", "rooms",
     "A suite alcove off the corridor, with a bench.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224838 http://teamwiess.com/newstudents/rooms/alcove.jpg]", "by 2017", "Rooms and spaces"),
    ("photos/freshmanroomnew.jpg", "rooms",
     "Plan of a double: two bedrooms, a common room and a bathroom.",
     "teamwiess.com, 2016", "[@wb 20160506224916 http://teamwiess.com/res/freshmanroomnew.png]", "by 2016", "Rooms and spaces"),
    ("photos-inside-rooms/commonroom.jpg", "rooms",
     "An empty suite common room, doors to the two bedrooms.",
     "teamwiess.com, 2016", "[@wb 20160506224917 http://teamwiess.com/res/commonroom.png]", "by 2016", "Rooms and spaces"),
    ("photos/beds.jpg", "rooms",
     "A double bedroom, two beds and two desks.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224845 http://teamwiess.com/newstudents/rooms/beds.jpg]", "by 2017", "Rooms and spaces"),
    ("photos-inside-rooms/desks.jpg", "rooms",
     "Wardrobes and dresser in a bedroom.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224844 http://teamwiess.com/newstudents/rooms/desks.jpg]", "by 2017", "Rooms and spaces"),
    ("photos-inside-rooms/onedesk.jpg", "rooms",
     "Desks under the window.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224846 http://teamwiess.com/newstudents/rooms/onedesk.jpg]", "by 2017", "Rooms and spaces"),
    ("photos-inside-rooms/bathroom-copy.jpg", "rooms",
     "A suite bathroom: two sinks, a large mirror, the shower.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224848 http://teamwiess.com/newstudents/rooms/bathroom.jpg]", "by 2017", "Rooms and spaces"),
    ("photos-outside/hall.jpg", "rooms",
     "The corridor outside the suites: doors and windows on one side, the Acabowl on the other.",
     "teamwiess.com, 'New students: rooms', 2017", "[@wb 20170714224842 http://teamwiess.com/newstudents/rooms/hall.jpg]", "by 2017", "Rooms and spaces"),
    # --- Team Wiess
    ("photos-people/teammerh.jpg", "teamwiess",
     "The TEAM / FAMILY / WIESS paper banners in the Commons, hung in a descending diagonal, behind an O-Week skit (video still, 2017).",
     "teamwiess.com, O-Week videos, 2017", "[@wb 20170908225508 http://teamwiess.com/newstudents/videos/teammerh.png]", "2017", "Team Wiess"),
    ("photos-outside/family-med.jpg", "teamwiess",
     "TEAM FAMILY WIESS on the Commons windows.",
     "teamwiess.com, 'acapics', by 2019", "[@wb 20190928044413 http://teamwiess.com/acapics/family.jpg]", "by 2019", "Team Wiess"),
    ("photos-people/daa.jpg", "teamwiess",
     "Jumping over the letters T F W, for the new students' pages.",
     "teamwiess.com, new students, 2019", "[@wb 20190802225456 http://teamwiess.com/newstudents/thumbnails/daa.jpg]", "by 2019", "Team Wiess"),
    # --- Symbols
    ("graphics/wiessshield1.jpg", "symbols",
     "The Wiess arms in color: a griffin counterchanged on a shield divided black over gold, a helmet with mantling, an owl on top.",
     "teamwiess.com, 2014", "[@wb 20140627224637 http://teamwiess.com/images/wiessshield1wtrans-u213-fr.png]", "by 2014", "Crest and colors"),
    ("graphics/crestbw.jpg", "symbols",
     "The crest in black and white.",
     "teamwiess.com, 2015", "[@wb 20150612230209 http://teamwiess.com/assets/crestbw.gif]", "by 2015", "Crest and colors"),
    ("graphics/wiess60-crest.jpg", "symbols",
     "The 60th-anniversary crest, 'Wiess College 60th Anniversary 1957–2017'.",
     "teamwiess.com/60, 2017", "[@wb 20170602224644 http://teamwiess.com/60/Wiess60-crest-with-date-small.png]", "2017", "Crest and colors"),
    ("graphics/wiess60-banner.jpg", "symbols",
     "The 60th-anniversary banner.",
     "teamwiess.com/60, 2017", "[@wb 20170602224639 http://teamwiess.com/60/Wiess60-banner.png]", "2017", "Crest and colors"),
    # --- NOD
    ("nod/themes-graphic.jpg", "nod",
     "'Themes through the decades', 1973–75 to 2011: a graphic of unknown origin, transcribed in the table above.",
     "Image of unknown origin, in the TFWKB NOD images", "", "c.2011–12", "Night of Decadence"),
    ("nod/1985-3.jpg", "nod",
     "NOD 'Animal Farm', 26 October 1984: paper pigs and animals hung over the crowd, the 12-foot pig at top left.",
     "The Campanile 1985, p.283", "[@campanile-1985]", "1984-10-26", "Night of Decadence"),
    ("nod/1983.jpg", "nod",
     "Dancing at NOD, c.1983 (date from the file name).",
     SOURCE_NOT_RECORDED_CREDIT, "", "c.1983", "Night of Decadence"),
    ("nod/1998-lg.jpg", "nod",
     "Three costumes at NOD 1998, 'Silver Anniversary: NOD's Greatest Hits' (date from the file name).",
     SOURCE_NOT_RECORDED_CREDIT, "", "1998", "Night of Decadence"),
    # --- Gazilchers
    ("photos-outside/1970-wiess-water-fight.jpg", "gazilchers",
     "Water balloons launched from the west wing of Old Wiess. The file is dated 1970; an alumnus who was there dates it c.1961–62.",
     "Rice History Corner, 6 May 2011", "[@rhc 2011-05-06 friday-afternoon-follies-plus-a-campus-quiz] [@rhc 2011-05-06 friday-afternoon-follies-plus-a-campus-quiz comment by Dagobert Brito (Wiess '63), 7 May 2011]", "c.1961–70", "Gazilchers"),
    ("photos-outside/1970-water-fight.jpg", "gazilchers",
     "The same battery from the side: a stretched launcher on the Old Wiess stair landing.",
     "Rice History Corner, 6 May 2011", "[@rhc 2011-05-06 friday-afternoon-follies-plus-a-campus-quiz]", "c.1961–70", "Gazilchers"),
    # --- War Pig
    ("photos/warpig1.jpg", "warpig",
     "A black pig lettered TEAM WIESS: the picture beside 'The mighty War Pig' on the first website's traditions page.",
     "riceinfo Wiess site, 2000", "[@wb 20000526190203 http://riceinfo.rice.edu:80/projects/colleges/wiess/traditions/index.html]", "by 2000", "War Pig"),
    ("photos/10-copy.jpg", "warpig",
     "The orange commercial pig, TEAM WIESS, tethered in the New Wiess Acabowl over the Acatramp; the ivy screens of New Wiess behind.",
     SOURCE_NOT_RECORDED_CREDIT, "[@warpig-core-deck slide 32]", "2002–04", "War Pig"),
    # --- Jock Row, Norse Night
    ("photos/weiss-jocks-nd-047.jpg", "jockrow",
     "A banner in the Old Wiess Commons supporting the Wiess jocks. Undated; commenters guess the 1960s or early 1970s.",
     "Rice History Corner, 20 May 2016", "[@rhc 2016-05-20 friday-follies-go-wiess-jocks]", "undated (1960s–70s?)", "Jock Row"),
    ("photos/norse1small.jpg", "norse",
     "The Campanile photograph on the 1999 Norse Night page: a Viking-table diner, napkin on head.",
     "riceinfo Wiess site, 1999 (a Campanile photograph)", "[@riceinfo-norse]", "before 1999", "Norse Night"),
    # --- Baker 13, Powderpuff, Beer Bike, Summit, O-Week
    ("photos-people/baker13defense.jpg", "b13",
     "The Baker 13 Defense Force representatives' photograph: suits, sunglasses and a water gun.",
     "teamwiess.com, representatives, 2017", "[@wb 20170421224913 http://teamwiess.com/profiles/reps/baker13defense.jpg]", "2017", "Baker 13 Defense Force"),
    ("photos/powderpuff-low.jpg", "powderpuff",
     "The Wiess powderpuff team at night, in black jerseys.",
     "teamwiess.com, by January 2023", "[@wb 20230114010452 http://teamwiess.com/images/powderpuff-low.jpg]", "by 2023", "Battle Sows & Powderpuff"),
    ("photos-people/beer-bike-low.jpg", "beerbike",
     "Wiess at Beer Bike in that year's maroon team shirts, faces painted, under the live oaks.",
     "teamwiess.com, by January 2023", "[@wb 20230114010426 http://teamwiess.com/images/beer-bike-low.jpg]", "by 2023", "Beer Bike"),
    ("photos-summit/2024.jpg", "summit",
     "Summit 2024: the college on the beach (date from the file name).",
     SOURCE_NOT_RECORDED_CREDIT, "", "2024", "Summit"),
    ("photos-oweek/2771146179-5e6a847fb9-c.jpg", "oweek",
     "O-Week, late 2000s: skateboarding in a goldenrod shirt.",
     "Flickr; photographer not recorded", "", "c.2008", "O-Week"),
    ("photos-oweek/2771950998-1fd704d707-c.jpg", "oweek",
     "O-Week, late 2000s: goldenrod shirts at a run.",
     "Flickr; photographer not recorded", "", "c.2008", "O-Week"),
    ("photos-oweek/2771989234-70da638bbe-c.jpg", "oweek",
     "O-Week, late 2000s: on the slip-and-slide.",
     "Flickr; photographer not recorded", "", "c.2008", "O-Week"),
    ("photos-people/coords.jpg", "oweek",
     "The 2021 O-Week coordinators ('coords' in the file name) in front of Lovett Hall, in YEAH WIESS shirts.",
     "teamwiess.com, O-Week 2021", "[@wb 20210619003837 http://teamwiess.com/images/oweek2021/coords.jpg]", "2021", "O-Week"),
    # --- Core Team
    ("photos/hutchinson.jpg", "coreteam",
     "John and Paula Hutchinson (Magisters c.1990–2001), in academic dress, from the Associates page.",
     "teamwiess.com, Associates, 2021", "[@wb 20210806235829 http://teamwiess.com/images/associates/hutchinson.png]", "by 2021", "Core Team"),
    ("photos-people/hudlow.jpg", "coreteam",
     "Doward and Christie Hudlow (RAs 2002–2008), from the Associates page.",
     "teamwiess.com, Associates, 2021", "[@wb 20210806235826 http://teamwiess.com/images/associates/hudlow.png]", "by 2021", "Core Team"),
    ("photos-people/masters2-1.jpg", "coreteam",
     "Mike Gustin and Denise Klein (Magisters 2006–2011), on the 2008 website.",
     "teamwiess.com, 2008", "[@wb 20080709214750 http://teamwiess.com/images/people/masters2.jpg]", "by 2008", "Core Team"),
    ("photos-people/byrd.jpg", "coreteam",
     "Alexander and Jeanette Byrd (Magisters 2011–2016) with their family.",
     "teamwiess.com, 2016", "[@wb 20160506224920 http://teamwiess.com/res/byrd.png]", "by 2016", "Core Team"),
    ("photos-people/renata-and-lenin-gavin235x156-1.jpg", "coreteam",
     "Renata Ramos and Lenin Terrazas (RAs 2011–2018) with their son.",
     "teamwiess.com; capture not identified", "", "2011–18", "Core Team"),
    ("photos-people/emilie.jpg", "coreteam",
     "Dr. Emilie Ringe (RA 2014–2017).",
     "teamwiess.com, 2016", "[@wb 20160506224923 http://teamwiess.com/res/emilie.png]", "by 2016", "Core Team"),
    ("photos-people/ewart-2.jpg", "coreteam",
     "Ewart G. Jones, Jr. (College Coordinator 2013–2023).",
     "teamwiess.com, 2016", "[@wb 20160506224925 http://teamwiess.com/res/ewart.png]", "by 2016", "Core Team"),
    ("photos-people/schaefers-2.jpg", "coreteam",
     "Drs. Andrew and Laura Schaefer (Magisters 2016–2021) with their family.",
     "teamwiess.com, 2016", "[@wb 20160527224834 http://teamwiess.com/res/schaefers.jpg]", "by 2016", "Core Team"),
    ("photos-people/carissa-nick.jpg", "coreteam",
     "Carissa Zimmerman and Nick Espinosa (RAs from 2018).",
     "teamwiess.com, 2020", "[@wb 20200529230221 http://teamwiess.com/images/carissa-nick.jpg]", "by 2020", "Core Team"),
    ("photos-people/flavio-fabiana.jpg", "coreteam",
     "Flavio Cunha and Fabiana Santos (Magisters from 2021).",
     "teamwiess.com, 2021", "[@wb 20210813231053 http://teamwiess.com/images/ateam/flavio-fabiana.jpeg]", "by 2021", "Core Team"),

    # --- Old Wiess, wing by wing (first website, 1998-99)
    ("riceinfo-1997-2002/views-ten1.jpg", "oldwiess1999",
     'The Tennis Court Wing, rooms 101–110 and 201–210; rooms 209–210 were the apartment of the Resident Associate, Dr. Stan Dodds.',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 20011112112601 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/tennis.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-ten2.jpg", "oldwiess1999",
     'The Tennis Court Wing from the Acabowl, with the bike rack on the right.',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 20011112112601 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/tennis.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-acab.jpg", "oldwiess1999",
     'The Acabowl Ledge, rooms 111–124: "especially if it\'s sunny, this ledge is one of the more active areas at Wiess."',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 20020116233355 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/acabowl.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-uaca.jpg", "oldwiess1999",
     'The second-floor Acabowl hallway, rooms 211–224 ("even the fire hose is in the same place").',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 20020116233355 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/acabowl.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-far.jpg", "oldwiess1999",
     'The Acabowl ledges from the intramural fields; the Acabowl was "home to a volleyball court, a few barbeque pits, some benches".',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 20020116233355 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/acabowl.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-3mid.jpg", "oldwiess1999",
     'The Middle Section, the only part of Old Wiess with a third floor: "the tower" (rooms 135–136, 235–236, 335 the computer room and 336 the presidential suite), with the five-man suites beside it.',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 19991011025731 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/tower.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-mid.jpg", "oldwiess1999",
     'The Middle Section from the Bacabowl side, rooms 134 (left) to 129 (right).',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 19991011025731 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/tower.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-fbaca.jpg", "oldwiess1999",
     'The Bacabowl Ledge, rooms 137/237–148/248, "generally a little bit quieter than the acabowl". Room 137 was a restroom, the "O/C Bathroom".',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 20020615221715 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/backabowl.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-fsing.jpg", "oldwiess1999",
     'The Singles Wing from the Bacabowl: "filled mostly with seniors"; Dr. Bill lived on the second floor, last room on the right.',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 19991011005025 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/singles.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-sing.jpg", "oldwiess1999",
     'The other side of the Singles Wing, facing Baker.',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 19991011005025 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/singles.html]', "1998–1999", "Old Wiess"),
    ("riceinfo-1997-2002/views-fish-room.jpg", "oldwiess1999",
     '"A typical Wiess freshman room", shot through a window with the last exposure on the roll; about 20 by 15 feet.',
     "First Wiess website, 'Pictures of Wiess Rooms' (set up by Head Fellow Chris Ruehl, 1998; text Ray Wagner, 1999)", '[@wb 19991011000933 http://riceinfo.rice.edu/projects/colleges/wiess/college/photos/frosh.html]', "1998–1999", "Old Wiess"),
    # --- Battle Sows 1999 (first website)
    ("riceinfo-1997-2002/sows-dasows.jpg", "powderpuff",
     'The Battle Sows, 1999 Powder Puff champions.',
     "First Wiess website, Battle Sows page, 1999", "[@riceinfo-battlesows]", "1999", "Battle Sows"),
    ("riceinfo-1997-2002/sows-huddle.jpg", "powderpuff",
     "The Sows' huddle, 1999.",
     "First Wiess website, Battle Sows page, 1999", "[@riceinfo-battlesows]", "1999", "Battle Sows"),
    ("riceinfo-1997-2002/sows-whattime.jpg", "powderpuff",
     'Battle Sows, 1999: "What time is it?"',
     "First Wiess website, Battle Sows page, 1999", "[@riceinfo-battlesows]", "1999", "Battle Sows"),
    # --- Core team portraits (first website)
    ("riceinfo-1997-2002/peepul-associates-drbill-tn.jpg", "coreteam",
     "Dr. Bill Wilson, Resident Associate, as pictured on the first website's Associates page.",
     "First Wiess website, People pages, 1998–2000", "[@riceinfo-masters]", "1998–2000", "Core Team"),
    ("riceinfo-1997-2002/peepul-associates-standodds-tn.jpg", "coreteam",
     'Dr. Stan Dodds, Resident Associate.',
     "First Wiess website, People pages, 1998–2000", "[@riceinfo-masters]", "1998–2000", "Core Team"),
    ("riceinfo-1997-2002/peepul-johnhutchinson2.jpg", "coreteam",
     'John Hutchinson, Magister (then Master).',
     "First Wiess website, People pages, 1998–2000", "[@riceinfo-masters]", "1998–2000", "Core Team"),
    ("riceinfo-1997-2002/peepul-paulahutchinson2.jpg", "coreteam",
     'Paula Hutchinson, Magister (then Master).',
     "First Wiess website, People pages, 1998–2000", "[@riceinfo-masters]", "1998–2000", "Core Team"),
]

# gallery_key -> (page_path relative to docs/, heading for the gallery's section on the Photographs page).
# Order here is the order of sections on the Photographs page. Two keys may share a page.
GALLERY_PAGES = {
    "oldwiess": ("places/old-wiess.md", "Old Wiess"),
    "oldwiess1999": ("places/old-wiess.md", "Old Wiess, wing by wing (1999)"),
    "commons": ("places/commons.md", "The Commons and UpCo"),
    "newwiess": ("places/new-wiess.md", "New Wiess"),
    "acabowl": ("places/acabowl.md", "The Acabowl"),
    "terraces": ("places/terraces.md", "The terraces and Toke"),
    "rooms": ("places/rooms-and-spaces.md", "Rooms and spaces of New Wiess"),
    "teamwiess": ("traditions/team-wiess.md", "Team Wiess and TFW"),
    "symbols": ("traditions/symbols.md", "Crest, colors and symbols"),
    "nod": ("traditions/night-of-decadence.md", "Night of Decadence"),
    "gazilchers": ("traditions/retired/gazilchers.md", "Gazilchers"),
    "warpig": ("traditions/warpig.md", "The War Pig"),
    "jockrow": ("traditions/retired/jock-row.md", "Jock Row"),
    "norse": ("traditions/retired/norse-night.md", "Norse Night"),
    "b13": ("traditions/baker-13-defense-force.md", "Baker 13 Defense Force"),
    "powderpuff": ("traditions/battle-sows-powderpuff.md", "Battle Sows & Powderpuff"),
    "beerbike": ("traditions/beer-bike.md", "Beer Bike"),
    "summit": ("traditions/summit.md", "Summit"),
    "oweek": ("traditions/o-week.md", "O-Week"),
    "coreteam": ("people/core-team.md", "The Core Team"),
}
